# ASP.NET Core 2.2
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

pool:
  vmImage: "Ubuntu 16.04"

variables:
  buildConfiguration: "Release"

steps:
  - task: DotNetCoreInstaller@0
    displayName: "Dotnet core installer 2.2.100"
    inputs:
      version: "2.2.100"
      packageType: "sdk"

  - task: DotNetCoreCLI@2
    inputs:
      command: restore
      projects: "**/*.csproj"

  - task: DotNetCoreCLI@2
    inputs:
      command: test
      projects: "**/*Tests*/*.csproj"
      arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

  - script: |
      dotnet build --configuration $(buildConfiguration)

  - task: DotNetCoreCLI@2
    inputs:
      command: publish
      publishWebProjects: True
      arguments: "--configuration $(buildConfiguration) --output $BUILD_ARTIFACTSTAGINGDIRECTORY"
      zipAfterPublish: True

  - task: PublishBuildArtifacts@1
